### ISSUE TITLE
Open-ended evolution

### ISSUE THREAD

**Issue by xkapastel** [primaryobjects/genetic-programming#1]
Hi, I was wondering if you'd be interested in another genetic programming challenge: evolving an expression tree that evaluates to the largest number possible. It's a bit different from your current examples as it doesn't involve a target output, but I think that makes it more exciting and leads to more interesting approaches to evolution. You will probably need to use a big number library to do it, though.

There is also a [Brainfuck](http://lambda-the-ultimate.org/node/5545) variant of this game, if you're still interested in using your code from "AI-Programmer".

**Comment by primaryobjects** [comment]
That sounds interesting. Please feel free to create a demo and share! :)
